language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

before_script:
  - chmod +x gradlew
  - printf "bintray.user=lodlock\nbintray.apikey=notreal\nbintray.gpg.password=stillnotreal" > ./local.properties

script:
  - ./gradlew build connectedCheck