language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

before_script:
  - chmod +x gradlew

script:
  - ./gradlew build connectedCheck